#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=runtime
WORKDIR /src
COPY ["DuckBank.Ahorros.Api.csproj", "."]
RUN dotnet restore "DuckBank.Ahorros.Api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./DuckBank.Ahorros.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=runtime
RUN dotnet publish "./DuckBank.Ahorros.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DuckBank.Ahorros.Api.dll"]

# docker build -t dotnet_duckbank_ahorros .
# docker run -d -p 3026:80 --name duckbank dotnet_duckbank_ahorros